version: "3.8"
services:
  my-sql: 
    image: mysql:8.0
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: covid-19
      MYSQL_USER: quangnm
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data/mysql:/val/lib/mysql