import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '../redux/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className} style={{margin: 0}}>{children}</body>
            </html>
        </Providers>
    );
}
